# Generated by Django 5.1.2 on 2025-01-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='list_num',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
