# Generated by Django 5.1.2 on 2025-01-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_list_num_alter_listing_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_num',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
