# Generated by Django 5.1.2 on 2025-01-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_list_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_num',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
