# Generated by Django 5.1.2 on 2025-01-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_listing_list_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='list_num',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
