# Generated by Django 5.1.2 on 2025-02-18 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listing_list_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
