# Generated by Django 5.1.2 on 2025-02-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_mhta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mhta',
        ),
    ]
